CUDA_VISIBLE_DEVICES=0 python3 main.py \
--mode train \
--batch_size 8 \
--accumulate_grad_batches 8 \
--dataset lastfm \
--data_dir data/ref/lastfm \
--cans_num 20 \
--llm_tuning lora \
--llm_path /workspace/Llama-2-7b-hf \
--output_dir output/adaptrec_lastfm \
--log_dir adaptrec_lastfm_logs \
--lr_warmup_start_lr 2e-6 \
--lr 2e-4 \
--lr_decay_min_lr 2e-6 \
--max_epochs 5 \
--precision bf16 \
--unsloth 1
